name: smart_class_app
description: Smart Class Check-in & Learning Reflection App (MVP)
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.15.2
  cloud_firestore: ^5.6.6
  flutter_dotenv: ^5.2.1
  geolocator: ^13.0.2
  mobile_scanner: ^6.0.2
  shared_preferences: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
